[package]
name = "mylang"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
insta = { version = "1.38.0", features = ["yaml"] }
serde = { version = "1.0.198", features = ["derive"] }
